runtime: python311

env: flex

entrypoint: gunicorn -b :8000 gym_api.wsgi:application

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 3
  cpu_threshold: 80

env_variables:
  DJANGO_SECRET_KEY: "django-insecure-cypkvo++so(u@x09w$&b*6f81+9-z6a&2)$7v5#v_gnzt%ey7)"
  DB_NAME: "postgres_new"
  DB_USER: "postgres_new"
  DB_PASSWORD: "PKp7nYu#_%~}1K2I"
  DB_HOST: "/cloudsql/brave-set-409318:us-central1:myowndb"
  # Exemplo: seu_id_do_projeto:us-central1:meu-banco-de-dados

beta_settings:
  cloud_sql_instances: "brave-set-409318:us-central1:myowndb"

# Opcional: se você estiver servindo arquivos estáticos ou de mídia diretamente pelo Django
# (não recomendado para produção), você pode configurar handlers para esses arquivos.
handlers:
- url: /static
  static_dir: static/
- url: /media
  static_dir: media/
