# Generated by Django 5.0.3 on 2024-03-11 17:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='customuser',
            name='data_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
