# Generated by Django 5.0.3 on 2024-03-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0002_alter_diet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='mealtype',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
